### ISSUE TITLE
Just run your example. and not working

### ISSUE THREAD

**Issue by johngalt13** [dsbowen/flask-download-btn#1]
Hi there,
I just run your example 
and got - 

{{ download_btn.script() }}

jinja2.exceptions.UndefinedError: '__main__.DownloadBtn object' has no attribute 'script'

**Comment by dsbowen** [comment]
Thank you for bringing this to my attention! The example on the home page was out of date. Use  `download_btn.render_script()` instead of `download_btn.script()`. I've corrected this in the docs.
